CREATE TABLE CUSTOMERS (
    CustomerID INT PRIMARY KEY,
    FullName VARCHAR(100),
    Email NVARCHAR(100),
    Age INT
);

ALTER TABLE CUSTOMERS
MODIFY FullName VARCHAR(100) NOT NULL,
MODIFY Email NVARCHAR(100) NOT NULL,
ADD CONSTRAINT uq_email UNIQUE(Email),
MODIFY Age INT NOT NULL,
ADD CONSTRAINT chk_age CHECK(Age >= 0);